py::class_<BC_GatedMLP, std::shared_ptr<BC_GatedMLP>>(m, "BC_GatedMLP").def
(
    py::init<
        at::Tensor,
        at::Tensor,
        at::Tensor,
        at::Tensor,
        c10::optional<at::Tensor>,
        c10::optional<at::Tensor>,
        c10::optional<at::Tensor>,
        int,
        bool,
        bool,
        bool,
        bool,
        bool,
        std::shared_ptr<BC_LinearEXL3>,
        std::shared_ptr<BC_LinearEXL3>,
        std::shared_ptr<BC_LinearEXL3>,
        float
    >(),
    py::arg("guh"),
    py::arg("gu"),
    py::arg("a"),
    py::arg("down_xh"),
    py::arg("gu_ptrs_trellis"),
    py::arg("gu_ptrs_suh"),
    py::arg("gu_ptrs_svh"),
    py::arg("gu_K"),
    py::arg("gu_mcg"),
    py::arg("gu_mul1"),
    py::arg("act_silu"),
    py::arg("act_gelu"),
    py::arg("act_relu2"),
    py::arg("gate"),
    py::arg("up"),
    py::arg("down"),
    py::arg("act_limit")
)
.def("run_bszN", &BC_GatedMLP::run_bszN);

py::class_<BC_MLP, std::shared_ptr<BC_MLP>>(m, "BC_MLP").def
(
    py::init<
        c10::optional<at::Tensor>,
        at::Tensor,
        at::Tensor,
        c10::optional<at::Tensor>,
        bool,
        bool,
        bool,
        std::shared_ptr<BC_LinearEXL3>,
        std::shared_ptr<BC_LinearEXL3>,
        float,
        int,
        int
    >(),
    py::arg("xp"),
    py::arg("u"),
    py::arg("ones"),
    py::arg("yp"),
    py::arg("act_silu"),
    py::arg("act_gelu"),
    py::arg("act_relu2"),
    py::arg("up"),
    py::arg("down"),
    py::arg("act_limit"),
    py::arg("hidden_size"),
    py::arg("out_size")
)
.def("run_bsz1", &BC_MLP::run_bsz1);
